# Evaluación del personal existente y nuevas contrataciones 

## Preparación de las evaluaciones del desempeño.

El objetivo de la evaluación es proporcionar una descripción exacta y confiable de la manera en que el empleado lleva a cabo el puesto, esto es muy común en los seguros, ya que ellos tienen informes confidenciales, la cuál es de vital importancia para la empresa en general, cómo para los usuarios. Los sistemas de evaluación deben estar directamente relacionados con el puesto y ser prácticos y confiables. Es necesario que tengan niveles de medición o estándares completamente verificables, esto nos demuestra que tan confiable podemos ser con uno y otro empleado y que tanto se le puede delegar, para evitar un factor de riesgo.

Por estar directamente relacionados con el puesto se entiende que el sistema califica únicamente elementos de importancia vital para obtener éxito en el puesto. Si la evaluación no se relaciona con el puesto, carece de validez. Se entiende que la evaluación es práctica cuando es comprendida por evaluadores y evaluados. Un sistema complicado puede conducir a confusión o generar suspicacia y conflicto.

** Ventajas de la evaluación del desempeño de los seguros.**

*	Políticas de compensación: puede ayudar a determinar quiénes merecen recibir aumentos.
*	Decisiones de ubicación: las promociones, transferencias y separaciones se basan en el desempeño anterior o en el previsto.
*	Necesidades de capacitación y desarrollo: el desempeño insuficiente puede indicar la necesidad de volver a capacitar, o un potencial no aprovechado, en los seguros tienen que estar constantemente capacitados, tanto como para tratar con los clientes/usuarios, como para resolver preguntas, la frecuencia con la que se capacita a un empleado, demuestra el que tan eficaz, eficiente es al momento de resolver un problema, también nos ayuda a prevenir el uso indebido de los datos que maneja en la empresa.
*	Planeación y desarrollo de la carrera profesional: guía las decisiones sobre posibilidades profesionales específicas, cuando tenemos un área específica, podemos tener una mayore respuesta a un posible problema, en el caso de un seguro, podemos visualizar a un especialista en ciberseguridad el cual nos brinde una total confianza con respecto a los datos que tenemos almacenados tanto en los servidores, como en usbs o cualquier otro dispositivo de almacenamiento.
*	Errores en el diseño del puesto: el desempeño insuficiente puede indicar errores en la concepción del puesto. Cuando hablamos de los seguros lo que menos queremos es tener que estar lidiando con un empleado que no está apto para el puesto que fue elegido, esto puede traer grandes problemas, como la pérdida de información, acceso a personal no clasificado, etc. por eso es muy importante saber que tan bueno es dicho empleado para desarrollar el cargo adquirido. junto con una buena capacitación.  
 
## Métodos de evaluación basados en el desempeño a futuro.
Se centran en el desempeño venidero mediante la evaluación del potencial del empleado o el establecimiento de objetivos de desempeño. En las empresas como los seguros se tienen que tomar en cuenta estas evaluaciones, ya que nos ayuda a determinar qué tan buenos son nuestros empleados.
1.	Autoevaluaciones: Cuando las autoevaluaciones se utilizan para determinar las áreas que necesitan mejorarse, pueden resultar de gran utilidad para la determinación de objetivos personales a futuro. El aspecto más importante de las autoevaluaciones radica en la participación del empleado y su dedicación al proceso de mejoramiento. Nos ayuda para una mejora constante, en el caso de los seguros, creamos equipos efectivos los cuales, tengan colaboración de ambas partes, con el fin de que los datos recabados de todos los usuarios tengan un buen manejo y no tengan un mal uso.  
2.	Administración por objetivos: consiste en que tanto el supervisor como el empleado establecen conjuntamente los objetivos de desempeño deseables. Lo ideal es que estos objetivos se establezcan por mutuo acuerdo y que sean mensurables de manera objetiva. Es necesario que el empleado reciba retroalimentación periódica. La retroalimentación nos ayuda al fortalecimiento de los empleados, este refuerzo nos beneficia porque así tenemos más presentes los aspectos en los cuales tenemos una mayor área de oportunidad, la cual también puede ser una de las causantes de la fuga de datos. Los empleados obtienen el beneficio de carácter motivacional de contar con una meta específica. 
Cuando los empleados y supervisores consideran objetivos que se miden por valores subjetivos se necesita especial cuidado para asegurarse de que no hay factores de distorsión que puedan afectar la evaluación.
3.	Evaluaciones psicológicas: El psicólogo prepara a continuación una evaluación de las características intelectuales, emocionales, de motivación y otras más, que pueden permitir la predicción del desempeño futuro. El trabajo de un psicólogo puede usarse sobre un aspecto específico o puede ser una evaluación global del potencial futuro. A partir de estas evaluaciones se pueden tomar decisiones de ubicación y desarrollo. Debido a que este procedimiento es lento y costoso, generalmente se reserva a gerentes jóvenes. Esto nos ayuda a determinar también qué tan fiable es nuestro personal, justo para determinar lo leal que alcanza con respecto a la empresa. 
4.	Métodos de los centros de evaluación: son una forma estandarizada para la evaluación de los empleados, que se basa en tipos múltiples de evaluación y múltiples evaluadores. Esta técnica suele utilizarse para grupos gerenciales de nivel intermedio que muestran gran potencial de desarrollo a futuro. Con frecuencia, se hace venir a un centro especializado a los empleados con potencial y se le somete a una evaluación individual. Este método es costoso en términos de tiempo y de dinero. Requiere además separar de sus funciones al personal que está en evaluación. Los resultados pueden ser muy útiles para ayudar al proceso de desarrollo gerencial y las decisiones de ubicación. Los seguros usan este método para tener buenos resultados con los empleados, ya que como es un centro evaluador externo, no tenemos por qué preocuparnos por tener, a elementos no funcionales para la empresa y no se selecciona de manera aleatoria, se selecciona por medio de una evaluación.


![Barcelo, J. (19–02-19). Evaluación del desempeño [Ilustración]. IMG Blog de recursos Humanos.](https://blogs.imf-formacion.com/blog/recursos-humanos/wp-content/uploads/2019/02/evaluacion-desempeno-gerente-rrhh-812x447.jpg)


