# Selección de personal. 
La selección de personal se define como un procedimiento para encontrar al hombre que cubra el puesto adecuado, es decir escoger entre los candidatos reclutados a los más adecuados, para ocupar los cargos existentes en la empresa, tratando de mantener o aumentar la eficiencia y el rendimiento del personal, en el caso específico de los seguros, se tiene que tomar en cuenta la ética de dichos prospectos, ya que el material con el que laboran es sensible y de alto valor.

*	Definir políticas y programas para garantizar la incorporación del personal idóneo a la entidad.
*	Seleccionar candidatos adecuados para el acceso, los traslados, las promociones y las actividades de formación y desarrollo.
 
**Principios fundamentales.**
*	Principio básico Idoneidad demostrada.
*	Necesario, factible y costeable. Es una inversión
*	Debe ser permanente y planificado, tanto para el nuevo ingreso como los movimientos internos y los planes de formación.
*	Proceso estructurado, flexible, dinámico y específico para cada puesto y entidad
*	Se realiza por personal calificado y entrenado.
*	Considera junto a los requisitos calificatorios y extracalificatorios los relativos a los riesgos y exigencias fisiológicas y psicológicas.
*	Está integrado al resto de los subsistemas del Sistema de Dirección de los Recursos Humanos.
 
**Son responsabilidades de los directores y Jefes de Departamento de la Dirección de la Empresa y Directores Generales de Unidades:**

*	Identificar trimestralmente las necesidades actuales y perspectivas de fuerza de trabajo en su unidad y enviarlas a la Dirección de Recursos Humanos (en lo adelante DRH)
*	Realizar acciones de reclutamiento externo independientemente de que existan o no solicitudes por parte de los trabajadores de la empresa.
*	Garantizar la realización o actualización de los Profesiogramas de los cargos que se necesiten cubrir.
*	Solicitar a la DRH que se libre la convocatoria de los cargos vacantes o de nueva creación que se necesitan cubrir.
*	Designar, en el caso de reclutamiento externo, un trabajador con experiencia en el puesto para aplicar una prueba de conocimientos sobre la actividad a desempeñar.
*	Decidir el candidato más idóneo para cubrir cargos vacantes o de nueva creación independientemente de la fuente de reclutamiento utilizada y en correspondencia con lo establecido por la legislación vigente.
*	Comunicar por escrito a la DRH la decisión tomada.
*	Garantizar el cumplimiento estricto de lo normado en este procedimiento.
 
**¿De qué manera puede ayudar estas herramientas en los seguros?**
Cada uno de estos puntos son fundamentales, para tener a un buen prospecto, un elemento adecuado para el sistema de trabajo.  Los seguros pueden llegar a clasificar a los elementos cuyas características sean favorables, ya sea en rendimiento en eficacia y eficiencia, determinando esto y en caso específico de los seguros tomando en cuenta que el elemento que se quiere contratar debe tener mucha ética, discreción, responsabilidad y que sepa acatar reglas. Estos puntos también tienen bastante peso en cuanto a la toma de decisión sobre ese elemento al cual se le dará la oportunidad de convertirse en un empleado.


![Pérez, O. (17–01-16). Proceso de reclutamiento [Ilustración]. PeopleNext.](https://info.corponet.com.mx/hubfs/Imported_Blog_Media/consejos_reclutamiento_y_seleccion-2.png)
